
== O’Reilly Style Guide and Word List

[[getting_started]]
== About O'Reilly Style

This style guide is for authors, copyeditors, and proofreaders working
on books of all formats. As writers and editors, we know that language
changes over time, so *please check back regularly for updates to terms
and conventions*. Recent additions will be set in bold for a few months.

Authors, please also consult the authoring documentation for the format
in which you’re writing
(http://docs.atlas.oreilly.com/writing_in_asciidoc.html[Asciidoc],
http://oreillymedia.github.io/HTMLBook/[HTMLbook],
https://docbook.org/[DocBook], or
http://oreillymedia.github.io/production-resources/word/[Word]). For
sponsored projects, please see our
https://oreil.ly/editorial-independence[statement of editorial
independence].

For term conventions, check our guide and word list first, then _The
Chicago Manual of Style_, 17th edition, then
_https://www.merriam-webster.com/[Merriam-Webster’s Collegiate
Dictionary]_. Use your book-specific word list (provided by production)
to document style choices that differ or are not covered here (e.g.,
A.M. or a.m., data center or datacenter).

To avoid unintentional bias, when writing about groups of people, check
the group’s advocacy organization for guidance on appropriate language.
O’Reilly aims to avoid the following problematic language and recommends
using resources such as the https://consciousstyleguide.com/[Conscious
Style Guide], the
https://itconnect.uw.edu/work/inclusive-language-guide[University of
Washington’s “IT Inclusive Language Guide”], and the
https://ncdj.org/style-guide[Disability Language Style Guide] for
alternatives.

Avoid language that is unnecessarily gendered (e.g., middleman, man
hours), violent (e.g., hit, kill), and otherwise exclusionary,
incendiary, or imprecise (e.g., crazy, dummy, master/slave, tribe).
Avoid associating positive or negative characteristics with colors that
are also associated, problematically, with people (blackbox, black hat,
white list, etc.). Always follow a person’s preference and note
exceptions, if necessary (e.g., quoting research that is decades old or
technology that has fallen behind the times).

For questions specific to your book or assignment, please consult with
your editor or production editor.

[[considering_electronic_formats]]
== Considering Electronic Formats

Because we use a single set of source files to produce the print and
electronic versions of our books, it’s important to keep all formats in
mind while writing and editing:

* Avoid using "above" and "below" to reference figures, tables,
examples, unnumbered code blocks, equations, etc. (e.g., "In the example
below…"). Using live cross references (e.g., "see Figure 2-1") is best,
but when that’s not possible, use "preceding" or "following," as the
physical placement of elements could be different in reflowable formats.
* Anchor URLs to text nodes whenever possible, like you would on a
website. See
https://oreillymedia.github.io/production-resources/styleguide/#links[Links]
for more information.
+
[[id-BeU0teho]]
Avoid anchoring URLs to generic words or phrases such as "here," "this
website," etc. Be as descriptive as possible because the print version
of your book renders hyperlinks like this: "text anchor
(http://url.example.com/[_http://url.example.com/_])."

For example, this:

____
Download the source code
(http://www.url.thisismadeup.com/[_http://www.url.thisismadeup.com_])
and install the package"
____

is more useful than this:

____
"Download the source code from this website
(http://www.url.thisismadeup.com/[_http://www.url.thisismadeup.com_])
and install the package."
____
* Long URLs will be shortened so that they’re easy for print readers to
type manually.
+
[[id-warning-amazon]]
Do not link to products on any sales channels other than oreilly.com,
including Apple, Google, or Amazon. Apple and Google will refuse to sell
content that links to products on Amazon. Vendors, please flag any links
to these sales channels and let the production editor know they exist.

Saying "XX book is available on Amazon"—sans link—is OK.

For information about formatting code in books written in Word or Google
Docs properly for conversion, see
https://oreillymedia.github.io/production-resources/styleguide/#formatting-code-in-word-yDsgtXca[Formatting
Code in Word].

[[orm_grammar_punctuation_etc]]
== O’Reilly Grammar, Punctuation, etc.

For any words or conventions not covered here, refer to _The Chicago
Manual of Style_, 17th edition and
_https://www.merriam-webster.com/[Merriam-Webster]_.

[[abbreviationsacronyms]]
=== Abbreviations & Acronyms

See the *_The Chicago Manual of Style_, 18th edition* for questions
about abbreviations and acronyms that are not covered here:

* A.M. and P.M. or a.m. and p.m.—be consistent.
* Acronyms should be capitalized when expanded only if the term is a
proper noun (and spelled that way by the company). For example, key
performance indicator (KPI), but Amazon Web Services (AWS).
* In units of measure, do not use a hyphen. For example, it’s 32 MB hard
drive, not 32-MB hard drive. (Though when the unit is spelled out, use a
hyphen, e.g., 32-megabyte hard drive.)
* K = 1,024; k = 1,000. So a 56 kbps modem is equal to 56,000 bps, while
64 K of memory is equal to 65,536.
* Many acronyms are common enough that they should be used without
expanding. For our books, that typically includes (but is not limited
to) AI when it stands for artificial intelligence, API (application
programming interface), CLI (command-line interface), CPU (central
processing unit), HTML (HyperText Markup Language), IP (Internet
Protocol), UI (user interface), UX (user experience), etc.
* United States and United Kingdom should be spelled out on first
mention. After that, just use the acronym with no periods (so, US or
UK).
* University degrees (e.g., B.A., B.S., M.A., M.S., Ph.D., etc.) can
appear with or without periods—just be consistent.



[[bibliographical_entries]]
=== Bibliographical Entries and Citations

When citing materials in bibliographies, reference lists, or footnotes,
use the “Notes and Bibliography” system from the
*https://www.chicagomanualofstyle.org/tools_citationguide.html[_The
Chicago Manual of Style_], 18th edition*. Chicago also has an
Author-Date system that some authors prefer, which is perfectly
acceptable. If there is no discernible consistency, suggest Chicago's
Notes for footnotes and Bibliography for endnotes or back matter.

Let your production editor know which of Chicago's systems you applied
by adding a note to the Word List Doc.

In general, when referring to another book within a book’s text, include
the author name(s) for up to two authors. For three or more authors,
state the first author name, followed by “et al.” (be sure to include
the period). On first reference, include author and publisher name. For
example, "You can find more information in _The Elements of Typographic
Style_ by Robert Bringhurst (H&M)," or "For more information, consult
Robert Bringhurst’s _The Elements of Typographic Style_ (H&M)." On
subsequent references, just use the book title.

When referencing an O’Reilly book within the text, note only "O’Reilly"
in parentheses, not "O’Reilly Media, Inc." References to other O’Reilly
books should be linked to the book’s
http://shop.oreilly.com/category/browse-subjects.do[catalog page].

Make sure that the catalog page is anchored to the book’s title, rather
than standing on its own like this: "See
http://shop.oreilly.com/product/0636920024033.do[_Programming F# 3.0_],"
and remember not to link to product pages where the book is available
for purchase (see
https://oreillymedia.github.io/production-resources/styleguide/##considering_electronic_formats[Considering
Electronic Formats]).

Footnotes should contain more than just a URL, whether a full citation
for the text the URL points to or context for where the link leads. For
example:

. For more information, see the Wikipedia entry on JavaScript
(https://en.wikipedia.org/wiki/JavaScript).
. Grove, John. 2015. “Calhoun and Conservative Reform.” _American
Political Thought_ 4, no. 2 (March): 203–27.
https://doi.org/10.1086/680389.

_Not_ this:

. https://en.wikipedia.org/wiki/JavaScript
. https://doi.org/10.1086/680389



[[code]]
=== Code

[[line-length-ZKs1FLck]]
==== Line Length

Maximum line length for code varies slightly between book formats.
Consult the table below to find the maximum line length for your book’s
series within Atlas v2. If writing in Word, please keep code within the
margins that appear in the Word template and indicate proper linebreaks
and indents for all code. Indent using spaces, not tabs.

[cols=",,,,,",options="header",]
|===
|*Series* |*Body (top-level code)* |*Examples* |*Lists* |*Readeraids*
|*Sidebars*
|*Animal (7x9)* |81 |85 |73 |57 |77

|*Animal 6x9* |64 |68 |56 |40 |60

|*Report 6x9* |64 |68 |56 |40 |60

|*Trade 6x9* |76 |72 |65 |80 |69

|*Cookbook* |81 |85 |73 |57 |77

|*Make 1-column* |89 |89 |81 |66 |39

|*Make 2-column* |45 |46 |35 |28 |40

|*Make Getting Started* |63 |67 |60 |51 |60

|*Nutshell* |71 |75 |67 |60 |75

|*Pocket Ref* |51 |55 |50 |42 |51

|*Theory in Practice* |81 |85 |77 |51 |83
|===

[[syntax-highlighting-zVsXIecp]]
==== Syntax Highlighting

We use a tool called Pygments to colorize code. In most books, code will
appear in black and white in the print book and in color in all
electronic formats, including the web pdf. If you’re an author, please
consult the http://pygments.org/docs/lexers/[list of available lexers]
and apply them to your code as you write. To apply syntax highlighting
in Asciidoc, consult
http://docs.atlas.oreilly.com/writing_in_asciidoc.html#syntax_highlighting[Writing
in AsciiDoc]. To apply syntax highlighting in DocBook, consult
http://chimera.labs.oreilly.com/books/1234000000058/ch02.html#syntax_highlighting[the
DocBook Authoring Guidelines]. To apply syntax highlighting in Word,
consult the
http://oreillymedia.github.io/production-resources/word/#syntax-highlighting[O’Reilly
Media Word Template Quickstart Guide].

[[formatting-code-in-word-yDsgtXca]]
===== Formatting Code in Word

When copyediting in Word, please do a global search and replace for tabs
in code (search for \^t to find them) before submitting files for
conversion; tabs _will not_ convert. A general rule of thumb is one tab
can be replaced with four spaces (which is the same number that the
clean-up macro in the ORA.dot template uses). However, this number can
vary, so the most important thing is that copyeditors replace tabs with
the numbers of spaces needed to match the indentation and make sure
levels of indentation are preserved.



[[cross_references]]
=== Cross References

Here are a few examples of cross references:

* Chapter: See Chapter 27.
* Section: See “Treatment” on page xx. (The text “on page xx” will be
dynamic in Atlas, updating as page numbers change.)
* Figure: ...as shown in Figure 1-1.
* Sidebars: See “A Note for Mac Users” on page xx. (As with section
xrefs, the page number will update automatically in Atlas.)

More details on cross-references in Asciidoc are available in our
http://docs.atlas.oreilly.com/writing_in_asciidoc.html#XREFS[Writing in
AsciiDoc] guide.

These cross-reference styles are also available in DocBook under various
<xref>: formats. Please refer to the
http://chimera.labs.oreilly.com/books/1234000000058/ch02.html#creating_xrefs[DocBook
Authoring Guidelines].

For information about styling URLs and hyperlinks, see
https://oreillymedia.github.io/production-resources/styleguide/#considering_electronic_formats[Considering
Electronic Formats].



[[dates_and_numbers]]
=== Dates and Numbers

Here is some additional guidance on what to spell out and when:

* Always use the symbol % with numerals rather than the spelled out word
(percent), and make sure it is closed up to number: 0.05%. Unless the
percentage begins a sentence or title/caption, the number should be a
numeral with the % symbol.
* Centuries follow the same zero through nine rule, so those will
usually be numerals (i.e., 20th century, 21st century).
* In most numbers of one thousand or more, commas should be used between
groups of three digits, counting from the right (32,904 _NOT 32904_).
Exceptions: page numbers, addresses, port numbers, etc.
* Spell out numbers from zero to nine and certain round multiples of
those numbers unless the same object appears in a sentence with an
object 10 or over (five apples; five apples and one hundred oranges; 5
apples and 110 oranges).
* Spell out ordinal numbers first through ninth, use numerals for 10th
and above. No superscript.
* Use numerals for versions (version 5 or v5).
* Use a numeral if it’s an actual value (e.g., 5% 7″ $6.00).
* Whole numbers one through nine followed by hundred, thousand, million,
billion, and so forth are usually spelled out (except in the sciences or
with monetary amounts).

This is how we format dates and other numbers:

* 1980s or ’80s.
* 32-bit integer.
* Phone numbers can appear in the format xxx-xxx-xxxx.
* Use an en dash (–) with negative numbers or for minus signs, rather
than a hyphen.
* Use multiplication symbol “×” for dimensions, not "by" (e.g., "8.5 ×
11").
* Use spaces around inline operators (1 + 1 = 2. _NOT 1+1=2_).



[[figures_tables_and_examples]]
=== Figures, Tables, and Examples

Every formally numbered figure, table, and example should be preceded by
a specific in-text reference (for example: see Figure 99-1; Example 1-99
shows; Table 1-1 lists, etc.). Formal figures, tables, and examples
should not be introduced with colons or phrases like “in the following
figure,” or “as shown in this table.” Though we do support unnumbered
informal figures/tables/examples, these should be used only for elements
whose contents are not discussed at length or referred back to. Lack of
specific in-text references may cause incorrect placement of figures.
See
https://oreillymedia.github.io/production-resources/styleguide/#cross_references[Cross
References] for more detail on including cross references.

If you are writing or copyediting in Word, figure, table, and example
numbers should be numbered as follows: 1-2 (note hyphen [-], not en dash
[–] between numbers). The first number is the chapter number. This will
be soft-coded in production if not during the writing process.

If you are writing or copyediting in Asciidoc, please refer to
http://docs.atlas.oreilly.com/writing_in_asciidoc.html#XREFS[Writing in
AsciiDoc] for examples of Asciidoc cross references.

If you are writing or copyediting in DocBook, please reference each
figure, table, and example with an <xref>.

Any word groupings within a figure should have an initial cap on the
first word only, with the exception of proper nouns. Generally, we don’t
use periods at the end of these word groupings.

* Figure 1-1. Figure captions are sentence-cased, with the exception of
proper nouns. Code styling is allowed within the figure name or caption.
There is no period after figure captions. Exceptions should be discussed
with your production editor (e.g., if several long captions require
punctuation, we can collaborate on efficient ways to achieve
consistency).
* Table 1-1. Column heads and table titles are sentence-cased, with the
exception of proper nouns. Code styling is allowed within the table name
or caption. There is no period after table titles.
* Example 1-1. Example titles are sentence-cased, with the exception of
proper nouns. Code styling is allowed within the example name or
caption. There is no period after example titles.

When working in Word, make sure all table cells are tagged with a cell
paragraph tag, even if they’re blank. Any bold “headings” that appear
below the very first row of a table should be tagged CellSubheading
rather than CellHeading.

Also in Word, all figures must be within a FigureHolder paragraph
followed directly by a FigureTitle paragraph.



[[gen_ai]]
=== Generative AI

There are two main contexts where generative AI content appears:
chatbot/UI interactions, and code/programming interactions. The former
will appear in more non-technical books, while the latter is common in
books aimed at developers and engineers. Query production if you're not
sure what category something belongs in.

Display "conversational" text generated in an AI chatbot environment in
blockquotes. To separate a prompt from a response, showing who “said”
what, use italics:

____
_Prompt_: Can you write some text?

_(insert appropriate technology name here)_: Sure can!
____

We want to accurately replicate the back-and-forth between human and AI.
Human prompts can be edited very lightly (e.g., punctuation,
capitalization), but AI-generated text should be kept verbatim. If AI
output is edited for some reason, be sure to still acknowledge the AI's
contribution. It must be clear what is AI-generated.

Display content that has a programming context in a code block, with a
normal paragraph separating the prompt and the response as needed. The
code content should be left verbatim, for the most part, though typos
can be flagged for author/production attention. There will not be syntax
highlighting. Here is an example:

____
....
prompt = "Write an email apologizing to Sarah for the tragic gardening mishap. 
          Explain how it happened."

output = generator(prompt)

print(output[0]['generated_text'])
....

This generates the text:

....
Solution 1:

Subject: My Sincere Apologies for the Gardening Mishap

Dear Sarah,

I hope this message finds you well. I am writing to express my deep...
....
____



=== Headings

Headings should not contain inline code font or style formatting such as
bold, italic, or code font.

Headings should always immediately precede body text. Do not follow a
heading with an admonition or another heading without some form of
introductory or descriptive text.

Follow these rules for capitalization in headings:

* A- and B-level headings are initial-capped (or title case)in most of
our design templates. Capitalize the first letter of each word, with the
exception of articles, conjunctions, and program names or technical
words that are always lowercase.
* C-level headings have initial cap on the first word only (also called
sentence-case), with the exception of proper nouns and the first word
that follows a colon (unless that word refers to code and should be
lowercase).
* D-level headings (rare) are run-in with the following paragraph and
have an initial cap on the first word only, with the exception of proper
nouns and the first word that follows a colon (unless that word refers
to code and should be lowercase), with a period at the end of the
heading.
* Sidebar titles are initial-capped, or title case (like A- and B-level
headings, mentioned previously).
* Admonition (note/tip/warning) titles are initial-capped, or title case
(like A- and B-level headings, mentioned previously). Admonition titles
are optional.
* Hyphenated words should both be capped if the second word is a main
word, but only the first should be capped if the second word isn’t too
important (it’s a bit of a judgment call). For example: Big-Endian,
Built-in. See _The Chicago Manual of Style_.
* Prepositions of four letters or fewer are not initial-capped, unless
they function as part of a verb (e.g., “Set Up Your Operating System”).
* Subordinating conjunctions (e.g., as, if, that, because, etc.) are
always initial-capped (even if they are four letters or less).



=== Links

In books produced in Atlas, URLs should be anchored to descriptive text
where possible. In ebook versions, the markup will render like this:

* Navigate to the https://oreilly.com/[O'Reilly home page] for more
information.

In the print book, the URL will unfurl in a parenthetical after the
linked text:

* Navigate to the O'Reilly home page (_https://oreilly.com_) for more
information.

Because of this difference in appearance of links in ebooks and print
books, long and complex URLs are shortened during production. In the
past, we used bit.ly to shorten these URLs, but as of May 2019, all
shortened links will be hosted and tracked internally, using the
oreil.ly short link.

We do not anchor URLs to text in books produced in InDesign.

=== Lists

Typically, we use three types of lists: numbered lists, for ordered
steps or chronological items; variable lists, for terms and
explanations/definitions; and bulleted lists, for series of items. List
items are sentence-capped. List items should be treated as separate
items and should not be strung together with punctuation or
conjunctions. Unless one item in a list forms a complete sentence, the
list's items do not take periods. If one does form a complete sentence,
use periods for all items within that list, even fragments.

_NOT O'Reilly style:_

* _Here is an item, and_
* _here is another item; and_
* _here is the final item._

O'Reilly style:

* Here is an item.
* Here is another item.
* Here is the final item.

Following are examples of each type of list.

[[bulleted_list]]
==== Bulleted list

The following series of items is an example of a bulleted list:

* Labels
* Buttons
* Text boxes

“Bulleted” lists nested inside of bulleted lists should have em dashes
as bullets.

Frequently, bulleted lists should be converted to variable lists. Any
bulleted list whose entries consist of a short term and its definition
should be converted. For example, the following bulleted list entries:

* Spellchecking: process of correcting spelling
* Pagebreaking—process of breaking pages

should be variable list entries:

_Spellchecking_::
  Process of correcting spelling
_Pagebreaking_::
  Process of breaking pages

[[numbered_list]]
==== Numbered list

The following list of step-by-step instructions is an example of a
numbered list:

. Save Example 2-1 as the file _hello.cs_.
. Open a command window.
. From the command line, enter `+csc /debug hello.cs+`.
. To run the program, enter `+Hello+`.

[[variable_list]]
==== Variable list

The following list of defined terms is an example of a variable list:

_Setup project_::
  This creates a setup file that automatically installs your files and
  resources.
_Web setup project_::
  This helps deploy a web-based project.



=== Punctuation

For anything not covered in this list, please consult the *_Chicago
Manual of Style_, 18th edition*.

* Commas and periods go inside quotation marks.
* Curly quotes and apostrophes (“ ” not " ") in regular text.
* Ellipses are always closed (no space around them).
* Em dashes are always closed (no space around them).
* Footnote markers in running text should always appear _after_
punctuation (e.g., ".^1^" and _not_ "^1^.").
* Footnotes in running text are numbered and start over at 1 in each
chapter. (More details about styling footnotes in AsciiDoc are in
http://docs.atlas.oreilly.com/writing_in_asciidoc.html#adding_footnotes[Writing
in AsciiDoc].)
* For menu items that end with an ellipsis (e.g., "New Folder…"), do not
include ellipsis in running text.
* Lowercase the first letter after a colon: this is how we do it.
(Exception: headings.)
* No period after list items unless one item forms a complete sentence
(then use periods for all items within that list, even fragments).
* Parentheses are always roman, even when the contents are italic. For
parentheses within parentheses, use square brackets (here’s the first
parenthetical [and here’s the second]).
* Serial comma (this, that, and the other).
* Straight quotes (" " not “ ”) in constant-width text and all code.
Some Unix commands use backticks (`+\'+`), which must be preserved.
* Table footnotes are lettered (a, b, c, etc.) and appear directly after
the table. They should be kept to a minimum.

[[typography_and_font_conventions]]
=== Typography and Font Conventions

The following shows the basic font conventions used in O’Reilly books.
Follow these links for detailed instructions for applying these styles
in
http://docs.atlas.oreilly.com/writing_in_asciidoc.html#INLINES[Asciidoc],
http://chimera.labs.oreilly.com/books/1234000000058/index.html:[DocBook],
and
http://oreillymedia.github.io/production-resources/word/#paragraph-character-styles[Word].

If you want to use a font convention that is slightly different for one
of the following items, check with your editor first—some things can
change; some can’t. For example, URLs will not be anything but _italic_,
but you might come up with a different font convention for function
names or menu items. If you have a “new” element, please consult with
your editor about which font to use.

[width="100%",cols="50%,50%",options="header",]
|===
|Type of element |Final result
|Filenames, file extensions (such as .jpeg), and directory paths. |_Body
font italic_

|URLs, URIs, email addresses, domain names |_Body font italic_

a|
Emphasized words (shouting!).

Please use italics rather than bold for emphasis.

|_Body font italic_

|First instance of a technical term |_Body font italic_

|Code blocks |`+Constant width+`

|Registry keys |`+Constant width+`

|Language and script elements: class names, types, namespaces,
attributes, methods, variables, keywords, functions, modules, commands,
properties, parameters, values, objects, events, XML and HTML tags, and
similar elements. Some examples include: `+System.Web.UI+`, a `+while+`
loop, the `+Socket+` class, the `+grep+` command, and the `+Obsolete+`
attribute. |`+Constant width+`

|SQL commands (`+SELECT+`, `+INSERT+`, `+ALTER+` `+TABLE+`, `+CREATE+`
`+INDEX+`, etc.) |`+CONSTANT+` `+WIDTH+` `+CAPS+`

|Replaceable items (placeholder items in syntax); “username” in the
following example is a placeholder: `+login:+` _`+username+`_
|_`+Constant width italic+`_

|Commands or text to be typed by the user |*`+Constant width bold+`*

|Line annotations |_Body font italic_ (but smaller)

|Placeholders in paths, directories, URLs, or other text that would be
italic anyway
|_http://www.%3Cyourname%3E.com/[_http://www.<yourname>.com_]_

|Keyboard accelerators (Ctrl, Shift, etc.), menu titles, menu options,
menu buttons |Body text

|*Packages and libraries (e.g., NumPy, scikit-learn, TensorFlow, rJava,
etc.) are roman and cased according to convention.* |Body text
|===

These font conventions may vary slightly for each project; please
consult your editor, the production editor, or the freelance coordinator
if you have any questions. _Please note:_ Word authors should refer to
the http://docs.atlas.oreilly.com/writing_in_asciidoc.html#INLINES[Word
Template Quickstart Guide]; DocBook authors should refer to our
https://prod.oreilly.com/external/tools/docbook/docs/authoring/[DocBook
Authoring Guidelines] (username: guest; leave the password blank).

It’s _very_ important to follow tagging conventions for terms. The
method for applying conventions will vary depending on the format:
Word/OpenOffice, DocBook XML, or InDesign. Please consult with your
editor or _toolsreq@oreilly.com_ for instructions specific to each
environment.

For Word copyediting, please do the following before submitting files
for conversion: replace any tabs in code with the appropriate number of
spaces (see earlier section,
https://oreillymedia.github.io/production-resources/styleguide/#code[Code]);
convert any remaining Word comments to tagged Comment paragraphs
highlighted in blue; search for any manual linebreaks (^l) and delete or
replace with paragraph breaks as appropriate; and accept all changes and
make sure filenames adhere to house style.



== Miscellaneous

* Avoid obscenities and slurs, and obscure if included (grawlix, a
two-em dash, etc.)
* Avoid using the possessive case for singular nouns ending in “s,” if
possible. So, it’s “the Windows Start menu,” not “Windows’s Start menu.”
* Avoid wholesale changes to the author’s voice—for example, changing
the first-person plural (the royal “we”) to the first-person singular or
the second person. However, do try to maintain a consistency within
sentences or paragraphs, where appropriate.
* Close up words with the following prefixes (unless part of a proper
noun) “micro,” “meta,” “multi,” “pseudo,” “re,” “non,” “sub,” and "co"
(e.g., “multiusers,” “pseudoattribute,” “nonprogrammer,” “subprocess,”
"coauthor"). Exceptions are noted in the word list (e.g., "re-create,"
"re-identification").
* Common foreign terms (such as “en masse”) are roman.
* Companies are always singular. So, for example, “Apple emphasizes the
value of aesthetics in its product line. Consequently, it dominates the
digital-music market” is correct. “Apple emphasize the value of
aesthetics in their product line. They dominate the digital-music
market” is _not_. (Also applies to generic terms “organization,” “team,”
“group,” etc.)
* Do not stack admonitions, sidebars, or headings.
* Do not use a hyphen between an adverb and the word it modifies. So,
“incredibly wide table” rather than “incredibly-wide table.”
* Introduce unnumbered code blocks with colons.
* Use “between” for two items, “among” for three or more. Use “each
other” for two, “one another” for three or more.
* Use the American spellings of words when they differ.
* We advise using a conversational, user-friendly tone that assumes the
reader is intelligent but doesn’t have this particular knowledge
yet—like an experienced colleague onboarding a new hire. First-person
pronouns, contractions, and active verbs are all encouraged.
(Copyeditors: please check with your production editor if you wish to
suggest global changes to tone.)
* When referring to software elements or labels, always capitalize words
that are capitalized on screen. Put quotes around any multiword element
names that are lowercase or mixed case on screen and would thus be hard
to distinguish from the rest of the text (e.g., Click “Don’t select
object until rendered” only if necessary.)



[[cover-style]]
== O'Reilly Cover Copy

Use *_Chicago Manual of Style_, 18th edition* for anything not mentioned
here.

Bulleted lists on the back cover should begin with a capitalized word
and end with no punctuation. Even if the list item is a complete
sentence, it will not take a period.

Lowercase job attributions in cover copy as much as possible. Formal job
titles can be title case, and anything more informal should be lowercase
(most will fall in the second category). It is OK to mix casing if there
are multiple attributions with differing levels of formality. If the
attribution starts on a line of its own, it will be sentence-cased. For
example:

____
"This is a great book."

—Robin Linacre, lead author of _Splink_

"I read this every day."

—Sawyer Nyquist, Chief Engineering Officer, The Data Shop
____



[[word-list]]
== O’Reilly Word List

This section lists favored spelling variations and default conventions
for common terms, acronyms, and abbreviations. Use Merriam Webster’s
Collegiate Dictionary for anything not covered here.

[[wordlist-A]]
=== A

* a.k.a. or aka (be consistent)
* a.m. or A.M.
* acknowledgments
* ActionScript
* ActiveX control
* ad hoc
* Addison-Wesley
* ADO.NET
* Agile (cap when referring to Agile software development or when used
on its own as a noun)
* Ajax
* Alt key
* Alt-N
* anonymous FTP
* antipattern
* appendixes
* applet (or Java applet)
* AppleScript
* AppleScript Studio (ASS)
* ARPAnet
* ASCII
* ASP.NET
* at sign
* autogenerate
* awk



[[wordlist-B]]
=== B

* build-measure-learn cycle
* backend
* background processes
* backpressure
* backquote
* backslash
* Backspace key
* backtick
* backup (n); back up (v)
* backward compatible
* backward
* bash (avoid starting sentence with this word, but if unavoidable, cap
as Bash)
* BeOS
* Berkeley Software Distribution (BSD)
* Berkeley Unix (older books may have UNIX)
* BHOs
* big data
* Big Design Up Front (BDUF)
* bioinformatics
* bit mask
* bit plane
* Bitcoin (capitalize the concept/network/currency in general; lowercase
specific units of currency)
* bitmap
* Bitnet
* bitwise operators
* BlackBerry
* Boolean (unless referring to a datatype in code, in which case s/b
lowercase)
* Bourne shell
* Bourne-again shell (bash)
* braces or curly braces
* brackets or square brackets
* browsable
* built-in (a, n)
* button bar



[[wordlist-C]]
=== C

* C-language (a)
* <CR><LF>
* C language (n)
* C shell
* CacheStorage
* call-to-action
* Caps Lock key
* caret or circumflex
* CAT-5
* CD-ROM
* check-in (n)
* checkbox
* checkmark
* classpath
* click-through (a)
* client side (n)
* client-side (a)
* client/server
* cloud native (n or a)
* co-class
* coauthor
* code set
* codebase
* colorcell
* colormap
* Command key (Mac)
* command line (n)
* command-line (a)
* Common Object Request Broker Architecture (CORBA)
* compact disc
* compile time (n)
* compile-time (a)
* CompuServe
* Control key (Mac)
* copyleft
* copyright
* coworker
* criterion (s), criteria (p)
* cross-reference
* Ctrl key (Windows)
* curly braces or braces
* cybersecurity



[[wordlist-D]]
=== D

* data block
* Data Encryption Standard (DES)
* data is
* datacenter or data center (be consistent)
* datafile
* dataset or data set (be consistent)
* datatype or data type (be consistent)
* DB-9
* de-identification (hyphenate)
* Debian GNU/Linux
* decision making (n)
* decision-making (a)
* deep learning (n and a, no hyphen)
* Delete key
* design time (n)
* design-time (a)
* DevOps
* dial up (v)
* dial-up (a)
* disk-imaging software
* disk
* DNS
* DocBook
* Document Object Model (DOM)
* Domain Name System
* dot-com
* dot
* double quotes
* double-click
* double-precision (a)
* down arrow
* downlevel (a)
* drag and drop (v)
* drag-and-drop (n)
* drop-down (a)



[[worldlist-E]]
=== E

* eBay
* ebook
* ebusiness
* ecommerce
* Emacs
* email
* empty-element tag
* end user (n); end-user (a)
* end-of-file (EOF)
* end-tag
* Engines of Growth
* Enter key
* equals sign
* ereader
* Escape key (or Esc key)
* et al.
* Ethernet
* exclamation mark
* Exim



[[wordlist-F]]
=== F

* failback
* failover
* fax
* file manager
* file server
* file type
* filename
* filepath
* filesystem
* FireWire
* foreground
* Fortran 90
* FORTRAN
* forward (adv)
* frame type
* Free Documentation License (FDL)
* Free Software Foundation (FSF)
* FreeBSD
* frontend
* FTP (protocol)
* ftp (Unix command)
* FTP site
* full stack (Full Stack in headings), no hyphen, even if adjective



[[wordlist-G]]
=== G

* gateway
* Gb (gigabit)
* GB (gigabyte)
* GBps (gigabytes per second)
* GHz
* gid
* GIMP
* Git
* GitHub
* GNOME
* GNU Emacs
* GNU Public License (GPL)
* GNUstep
* Google PageRank
* grayscale
* greater-than sign or >
* greenlight (v)
* GUI, GUIs



[[wordlist-H]]
=== H

* handcode
* handoff (n)
* hard link
* hardcode (v)
* hardcopy
* hardcore
* hardware-in-the-loop
* hash sign or sharp sign
* high-level (a)
* home page
* hostname
* hotspot
* HTML
* HTTP
* hypertext



[[wordlist-I]]
=== I

* I/O
* IDE
* IDs
* IndexedDB
* infrastructure as a service (IaaS)
* inline
* inode
* interclient
* Internet of Things (IoT)
* internet, the internet
* internetwork
* intranet
* Intrinsics
* IP (Internet Protocol)
* IPsec
* ISO
* ISP



[[wordlist-J]]
=== J

* Jabber applet
* Jabber client
* Jabber server
* Jabber
* JAR archive
* JAR file
* JavaScript
* JPEG



[[wordlist-K]]
=== K

* K Desktop Environment (KDE)
* Kb (kilobit)
* KB (kilobyte) (denotes file size or disk space)
* Kbps (kilobits per second)
* keepalive (n or a)
* Kerberos
* key performance indicators (KPIs)
* keyclick
* keycode
* keymaps
* keypad
* keystroke
* keysym
* keywords
* kHz (kilohertz)
* Korn shell



[[wordlist-L]]
=== L

* lambda (lc unless referring to a product)
* Lean (capitalize noun or adjective when referring to Lean business
methodology)
* left angle bracket or <
* lefthand (a)
* leftmost
* less-than sign or <
* leveled (not levelled)
* life cycle or lifecycle (be consistent)
* line feed (n)
* line-feed (a)
* Linux Professional Institute (LPI)
* Linux
* LinuxPPC
* listbox
* local area network or LAN
* log in, log out, or log on (v)
* logfile
* login, logout, or logon (n or a)
* lower-level (a)
* lower-right (a)



[[wordlist-M]]
=== M

* Mac (or MacBook)
* machine learning (n and a, no hyphen)
* macOS
* mail-handling (adjective)
* manpage
* markup
* Mb (megabit)
* MB (megabyte)
* MBps (megabytes per second)
* McGraw-Hill
* menu bar
* Meta key
* Meta-N
* metacharacter
* MHz (megahertz)
* mice or mouses (be consistent)
* microservices
* Microsoft Windows 2000
* Microsoft Windows Me
* Microsoft Windows NT
* Microsoft Windows XP
* Microsoft Windows
* MIDlet
* MKS Toolkit
* model-in-the-loop
* MS-DOS
* Multi-Touch (when referring to Apple's trademark)
* multiline
* My Services
* MySpace



[[wordlist-N]]
=== N

* .NET
* name service
* nameserver
* namespace
* NetBIOS
* NetBSD
* NetInfo
* newline
* newsgroups
* NeXTSTEP
* NGINX (company), `+nginx+` (server)
* nonlocal
* NOOP
* NoSQL
* Novell NetWare
* the _New York Times_
* the Net



[[wordlist-O]]
=== O

* O’Reilly Media, Inc.
** O’Reilly’s platform s/b "the O’Reilly platform" or "the O’Reilly
learning platform" and then "O’Reilly" on subsequent mentions
* object linking and embedding (OLE)
* object request broker (ORB)
* object-oriented programming (OOP)
* Objective-C
* offline
* offload
* OK
* on premises (prep. phrase) on-premises (modifier); may be abbreviated
to on prem/on-prem
* online
* open source (n or a, rewrite to avoid using in a verb form)
* open source software (OSS)
* OpenBSD
* OpenMotif
* OpenStep
* OpenWindows
* Option key (Mac)
* Oracle 8.0
* Oracle 8__i__ (italic “i”)
* Oracle 9__i__ (italic “i”)
* Oracle Parallel Query Option
* Oracle7
* Oracle8
* OS/2
* OSA
* OSF/Motif



[[wordlist-P]]
=== P

* % (not percent)
* p.m. or P.M.
* packet switch networks
* page rank (but Google PageRank)
* pagefile
* Paint Shop Pro
* parentheses (p)
* parenthesis (s)
* Pascal
* pathname
* pattern-matching (a)
* peer-to-peer (or P2P)
* performant (Oracle)
* period
* Perl DBI
* Perl
* plain text (n)
* plain-text (a)
* platform as a service (PaaS)
* Plug and Play (PnP)
* plug in (v)
* plug-in (a, n)
* Point-to-Point Protocol (PPP)
* pop up (v)
* POP-3
* pop-up (n, a)
* Portable Document Format (PDF)
* Portable Network Graphics (PNG)
* Portable Operating System Interface (POSIX)
* POSIX-compliant
* Post Office Protocol (POP)
* postprocess
* PostScript
* Prentice Hall
* process ID
* progress bar
* pseudo-tty
* pseudoattribute
* public key (n)
* public-key (a)
* publish/subscribe or pub/sub
* pull-down (a)



[[wordlist-Q]]
=== Q

* qmail
* Qt
* QuarkXPress
* Quartz Extreme
* Quartz
* QuickTime
* quotation marks (spell out first time; it can be “quotes” thereafter)



[[wordlist-R]]
=== R

* random-access (a)
* RCS
* re-create
* re-identification (hyphenate)
* read-only (a)
* read/write
* real time (n)
* real-time (a)
* Red Hat Linux
* Red Hat Package Manager (RPM)
* redirection
* reference page or manpage
* remote-access server
* Rendezvous (_Mac OS X zeroconf networking_)
* Return (key)
* RFC 822
* rich text (n)
* rich-text (a)
* right angle bracket or greater-than sign (>)
* right-click
* righthand (a)
* rmail
* road map or roadmap (be consistent)
* rollback (n); roll back (v)
* rollout (n); roll out (v)
* rootkit
* Rubout key
* rulebase
* ruleset
* runtime (n, a)



[[wordlist-S]]
=== S

* Samba
* saveset
* screen dump
* screenful
* screensaver
* scroll bar
* Secure Shell (SSH)
* Secure Sockets Layer (SSL)
* securelevel (in Linux)
* sed scripts
* server side (n)
* server-dependent
* server-side (a)
* service worker
* servlet
* set up (v)
* setup (n)
* SGML
* sharp sign or hash sign
* shell (lowercase even in shell name: Bourne shell)
* shell scripts
* Shift key
* Simple API for XML (SAX)
* single quote
* single-precision (a)
* site map
* Smalltalk
* SMP (a, n)
* SOAP
* Social Security number (SSN)
* software as a service (SaaS)
* software-in-the-loop
* source code
* space bar
* spam (not SPAM)
* spellcheck
* spellchecker
* split screen
* square brackets or brackets
* standalone
* standard input (stdin)
* standard output (stdout)
* start tag
* startup file
* stateful
* stateless
* status bar
* stylesheet
* subprocess
* SUSE Linux
* swapfile
* swapspace
* sync
* system administrator
* system-wide



[[wordlist-T]]
=== T

* 10-baseT
* t-shirt
* TEX
* T1
* Tab key
* TAR file
* TCP/IP
* Telnet (the protocol)
* telnet (v)
* terabyte
* texinfo
* text box
* text-input mode
* thread pooling (n)
* time zone
* time-sharing processes
* timeout (in tech/computing contexts)
* timestamp
* title bar
* Token Ring
* tool tip
* toolbar
* toolchain
* toolkit
* top-level (a)
* toward
* trade-off
* tweet, retweet, live-tweet v, n (avoid “tweet out”)
* Twitterstorm, tweetstorm



[[wordlist-U]]
=== U

* UK (United Kingdom)
* Ultrix
* Universal Serial Bus (USB)
* Unix (UNIX in many books, esp. older ones)
* up arrow
* up-to-date
* upper- and lowercase
* upper-left corner
* uppercase
* UPSs
* URLs
* US (for United States)
* Usenet
* user ID (n)
* user-ID (a)
* username



[[wordlist-V]]
=== V

* v2 or version 2
* VAX/VMS
* VB.NET
* versus (avoid vs.)
* vice versa
* Visual Basic .NET
* Visual Basic 6 or VB 6
* Visual C++ .NET
* Visual Studio .NET
* VoiceXML
* Volume One
* VS.NET



[[wordlist-W]]
=== W

* the _Wall Street Journal_
* the web (n)
* web (a)
* web client
* web page
* web server
* web services (unless preceded by a proper noun, as in Microsoft Web
Services)
* webmaster
* website
* white pages
* whitepaper (I printed my whitepaper on white paper.)
* whitespace
* wide area network or WAN
* WiFi
* wiki
* wildcard
* Windows 2000
* Windows 95
* Windows 98
* Windows NT
* Windows Vista
* Windows XP
* wizard (a, n)
* Wizard (proper noun)
* workaround
* workbench
* workgroup
* workstation
* World Wide Web (WWW)
* wraparound
* writable
* write-only (a)
* WYSIWYG



[[wordlist-X]]
=== X

* (x,y) (no space)
* X client
* _x_ coordinate
* X protocol
* X server
* X Toolkit
* X Window series
* X Window System
* x-axis
* x86
* Xbox
* xFree86
* XHTML
* XLink
* XML Query Language (XQuery)
* XML-RPC
* XML
* XPath
* XPointer
* XSL
* XSLT
* XView



[[wordlist-Y]]
=== Y

* _y_ coordinate
* y-axis
* Yahoo!



[[wordlist-Z]]
=== Z

* Zeroconf (short for “Zero Configuration”)
* zeros
* zip (v)
* zip code
* ZIP file


