
=== O'Reilly Style Guide

For style conventions, check our guide and word list first, then _The
Chicago Manual of Style_, 18th edition, then
https://www.merriam-webster.com/[Merriam-Webster’s Collegiate
Dictionary].

==== URLs and Links

* Avoid using "above" and "below" to reference figures, tables,
examples, unnumbered code blocks, equations, etc. (e.g., "In the example
below…"). Using live cross references with the element ID (e.g., "see <<figure-21>>") is best,
but when that’s not possible, use "preceding" or "following," as the
physical placement of elements could be different in reflowable formats.

* Anchor URLs to text nodes whenever possible, like you would on a
website.

* Avoid anchoring URLs to generic words or phrases such as "here," "this
website," etc. Be as descriptive as possible.
+
For example, this:
+
____
Download the 
http://www.url.thisismadeup.com[source code]
and install the package"
____
+
is more useful than this:
+
____
"Download the source code from this website
(http://www.url.thisismadeup.com)
and install the package."
____

* Do not link to products on any sales channels other than oreilly.com,
including Apple, Google, or Amazon. Apple and Google will refuse to sell
content that links to products on Amazon. However, saying "XX book is available on Amazon"—sans link—is OK.

==== Abbreviations & Acronyms

* A.M. and P.M. or a.m. and p.m.—be consistent.
* Acronyms should be capitalized when expanded only if the term is a
proper noun (and spelled that way by the company). For example, key
performance indicator (KPI), but Amazon Web Services (AWS).
* In units of measure, do not use a hyphen. For example, it’s 32 MB hard
drive, not 32-MB hard drive. (Though when the unit is spelled out, use a
hyphen, e.g., 32-megabyte hard drive.)
* K = 1,024; k = 1,000. So a 56 kbps modem is equal to 56,000 bps, while
64 K of memory is equal to 65,536.
* Many acronyms are common enough that they should be used without
expanding. For our books, that typically includes (but is not limited
to) AI when it stands for artificial intelligence, API (application
programming interface), CLI (command-line interface), CPU (central
processing unit), HTML (HyperText Markup Language), IP (Internet
Protocol), UI (user interface), UX (user experience), etc.
* United States and United Kingdom should be spelled out on first
mention. After that, just use the acronym with no periods (so, US or
UK).
* University degrees (e.g., B.A., B.S., M.A., M.S., Ph.D., etc.) can
appear with or without periods—just be consistent.

==== Bibliographical Entries and Citations

* When citing materials in bibliographies, reference lists, or footnotes,
use the “Notes and Bibliography” system from the
*https://www.chicagomanualofstyle.org/tools_citationguide.html[_The
Chicago Manual of Style_], 18th edition*. Chicago also has an
Author-Date system that some authors prefer, which is perfectly
acceptable. If there is no discernible consistency, use Chicago's
Notes for footnotes and Bibliography for endnotes or back matter.

* In general, when referring to another book within a book’s text, include
the author name(s) for up to two authors. For three or more authors,
state the first author name, followed by “et al.” (be sure to include
the period). On first reference, include author and publisher name. For
example, "You can find more information in _The Elements of Typographic
Style_ by Robert Bringhurst (H&M)," or "For more information, consult
Robert Bringhurst’s _The Elements of Typographic Style_ (H&M)." On
subsequent references, just use the book title.

* When referencing an O’Reilly book within the text, note only "O’Reilly"
in parentheses, not "O’Reilly Media, Inc." References to other O’Reilly
books should be linked to the book’s
http://shop.oreilly.com/category/browse-subjects.do[catalog page].

* Footnotes should contain more than just a URL, whether a full citation
for the text the URL points to or context for where the link leads. For
example:
+
. For more information, see the https://en.wikipedia.org/wiki/JavaScript[Wikipedia entry on JavaScript].
. Grove, John. 2015. “Calhoun and Conservative Reform.” _American
Political Thought_ 4, no. 2 (March): 203–27.
https://doi.org/10.1086/680389.

+
_Not_ this:
+
. https://en.wikipedia.org/wiki/JavaScript
. https://doi.org/10.1086/680389


==== Dates and Numbers

* Always use the symbol % with numerals rather than the spelled out word
(percent), and make sure it is closed up to number: 0.05%. Unless the
percentage begins a sentence or title/caption, the number should be a
numeral with the % symbol.
* Centuries follow the same zero through nine rule, so those will
usually be numerals (i.e., 20th century, 21st century).
* In most numbers of one thousand or more, commas should be used between
groups of three digits, counting from the right (32,904 _NOT 32904_).
Exceptions: page numbers, addresses, port numbers, etc.
* Spell out numbers from zero to nine and certain round multiples of
those numbers unless the same object appears in a sentence with an
object 10 or over (five apples; five apples and one hundred oranges; 5
apples and 110 oranges).
* Spell out ordinal numbers first through ninth, use numerals for 10th
and above. No superscript.
* Use numerals for versions (version 5 or v5).
* Use a numeral if it’s an actual value (e.g., 5% 7″ $6.00).
* Whole numbers one through nine followed by hundred, thousand, million,
billion, and so forth are usually spelled out (except in the sciences or
with monetary amounts).
* This is how we format dates and other numbers:
** 1980s or ’80s.
** 32-bit integer.
** Phone numbers can appear in the format xxx-xxx-xxxx.
** Use an en dash (–) with negative numbers or for minus signs, rather
than a hyphen.
** Use multiplication symbol “×” for dimensions, not "by" (e.g., "8.5 ×
11").
** Use spaces around inline operators (1 + 1 = 2. _NOT 1+1=2_).

==== Figures, Tables, and Examples

* Every formally numbered figure, table, and example should be preceded by
a specific in-text reference using the element's ID (for example: see <<figure-1-99>>; <<example-1-99>>
shows; <<table-1-1>> lists, etc.). Formal figures, tables, and examples
should not be introduced with colons or phrases like “in the following
figure,” or “as shown in this table.” Though we do support unnumbered
informal figures/tables/examples, these should be used only for elements
whose contents are not discussed at length or referred back to.

* Figure captions are sentence-cased, with the exception of
proper nouns. Code styling is allowed within the figure name or caption. There is no period after figure captions. 
* Table column headings and table titles are sentence-cased, with the exception of proper nouns. Code styling is allowed within the table name or caption. There is no period after table titles.
* Example/listing titles are sentence-cased, with the exception of proper nouns. Code styling is allowed within the example name or caption. There is no period after example titles.

==== Headings

Headings should not contain inline code font or style formatting such as bold, italic, or code font.

Headings should always immediately precede body text. Do not follow a heading with an admonition or another heading without some form of introductory or descriptive text.

Follow these rules for capitalization in headings:

* A- and B-level headings are initial-capped (or title case)in most of
our design templates. Capitalize the first letter of each word, with the
exception of articles, conjunctions, and program names or technical
words that are always lowercase.
* C- and D-level headings have initial cap on the first word only (also called
sentence-case), with the exception of proper nouns and the first word
that follows a colon (unless that word refers to code and should be
lowercase).
* Sidebar titles are initial-capped, or title case (like A- and B-level headings, mentioned previously).
* Admonition (note/tip/warning) titles are initial-capped, or title case (like A- and B-level headings, mentioned previously). Admonition titles are optional.
* Hyphenated words should both be capped if the second word is a main
word, but only the first should be capped if the second word isn’t too
important (it’s a bit of a judgment call). For example: Big-Endian,
Built-in. See _The Chicago Manual of Style_.
* Prepositions of four letters or fewer are not initial-capped, unless
they function as part of a verb (e.g., “Set Up Your Operating System”).
* Subordinating conjunctions (e.g., as, if, that, because, etc.) are
always initial-capped (even if they are four letters or less).

==== Lists

Typically, we use three types of lists: numbered lists, for ordered
steps or chronological items; variable lists, for terms and
explanations/definitions; and bulleted lists, for series of items. List
items are sentence-capped. List items should be treated as separate
items and should not be strung together with punctuation or
conjunctions. Unless one item in a list forms a complete sentence, the
list's items do not take periods. If one does form a complete sentence,
use periods for all items within that list, even fragments.

_NOT O'Reilly style:_

* _Here is an item, and_
* _here is another item; and_
* _here is the final item._

O'Reilly style:

* Here is an item.
* Here is another item.
* Here is the final item.

Following are examples of each type of list.

===== Bulleted list

The following series of items is an example of a bulleted list:

* Labels
* Buttons
* Text boxes

Frequently, bulleted lists should be converted to variable lists. Any
bulleted list whose entries consist of a short term and its definition
should be converted. For example, the following bulleted list entries:

* Spellchecking: process of correcting spelling
* Pagebreaking—process of breaking pages

should be variable list entries:

_Spellchecking_::
  Process of correcting spelling
_Pagebreaking_::
  Process of breaking pages

===== Numbered list

The following list of step-by-step instructions is an example of a
numbered list:

. Save <<example-2-1>> as the file _hello.cs_.
. Open a command window.
. From the command line, enter `+csc /debug hello.cs+`.
. To run the program, enter `+Hello+`.

===== Variable list

The following list of defined terms is an example of a variable list:

_Setup project_::
  This creates a setup file that automatically installs your files and
  resources.
_Web setup project_::
  This helps deploy a web-based project.

===== Punctuation

* Commas and periods go inside quotation marks.
* Ellipses are always closed (no space around them).
* Em dashes are always closed (no space around them).
* Footnote markers in running text should always appear _after_
punctuation.
* For menu items that end with an ellipsis (e.g., "New Folder…"), do not
include ellipsis in running text.
* Lowercase the first letter after a colon: this is how we do it.
(Exception: headings.)
* No period after list items unless one item forms a complete sentence
(then use periods for all items within that list, even fragments).
* Parentheses are always roman, even when the contents are italic. For
parentheses within parentheses, use square brackets (here’s the first
parenthetical [and here’s the second]).
* Serial comma (this, that, and the other).
* Straight quotes (" " not “ ”) in constant-width text and all code.
Some Unix commands use backticks (`+\'+`), which must be preserved.

==== Typography and Font Conventions

|===
|Type of element |Final result
|Filenames, file extensions (such as .jpeg), and directory paths. |_Body
font italic_

|URLs, URIs, email addresses, domain names |_Body font italic_

a|
Emphasized words (shouting!).

Please use italics rather than bold for emphasis.

|_Body font italic_

|First instance of a technical term |_Body font italic_

|Code blocks |`+Constant width+`

|Registry keys |`+Constant width+`

|Language and script elements: class names, types, namespaces,
attributes, methods, variables, keywords, functions, modules, commands,
properties, parameters, values, objects, events, XML and HTML tags, and
similar elements. Some examples include: `+System.Web.UI+`, a `+while+`
loop, the `+Socket+` class, the `+grep+` command, and the `+Obsolete+`
attribute. |`+Constant width+`

|SQL commands (`+SELECT+`, `+INSERT+`, `+ALTER+` `+TABLE+`, `+CREATE+`
`+INDEX+`, etc.) |`+CONSTANT+` `+WIDTH+` `+CAPS+`

|Replaceable items (placeholder items in syntax); “username” in the
following example is a placeholder: `+login:+` _`+username+`_
|_`+Constant width italic+`_

|Commands or text to be typed by the user |*`+Constant width bold+`*

|Line annotations |_Body font italic_ (but smaller)

|Placeholders in paths, directories, URLs, or other text that would be
italic anyway
|_http://www.%3Cyourname%3E.com/[_http://www.<yourname>.com_]_

|Keyboard accelerators (Ctrl, Shift, etc.), menu titles, menu options,
menu buttons |Body text

|*Packages and libraries (e.g., NumPy, scikit-learn, TensorFlow, rJava,
etc.) are roman and cased according to convention.* |Body text
|===

==== Miscellaneous

* To avoid unintentional bias, when writing about groups of people, check
the group’s advocacy organization for guidance on appropriate language.
O’Reilly aims to avoid the following problematic language and recommends
using resources such as the https://consciousstyleguide.com/[Conscious
Style Guide], the
https://itconnect.uw.edu/work/inclusive-language-guide[University of
Washington’s “IT Inclusive Language Guide”], and the
https://ncdj.org/style-guide[Disability Language Style Guide] for
alternatives.
* Avoid language that is unnecessarily gendered (e.g., middleman, man
hours), violent (e.g., hit, kill), and otherwise exclusionary,
incendiary, or imprecise (e.g., crazy, dummy, master/slave, tribe).
Avoid associating positive or negative characteristics with colors that
are also associated, problematically, with people (blackbox, black hat,
white list, etc.). Always follow a person’s preference and note
exceptions, if necessary (e.g., quoting research that is decades old or
technology that has fallen behind the times).
* Avoid obscenities and slurs, and obscure if included (grawlix, a
two-em dash, etc.)
* Avoid using the possessive case for singular nouns ending in “s,” if
possible. So, it’s “the Windows Start menu,” not “Windows’s Start menu.”
* Avoid wholesale changes to the author’s voice—for example, changing
the first-person plural (the royal “we”) to the first-person singular or
the second person. However, do try to maintain a consistency within
sentences or paragraphs, where appropriate.
* Close up words with the following prefixes (unless part of a proper
noun) “micro,” “meta,” “multi,” “pseudo,” “re,” “non,” “sub,” and "co"
(e.g., “multiusers,” “pseudoattribute,” “nonprogrammer,” “subprocess,”
"coauthor"). Exceptions are noted in the word list (e.g., "re-create,"
"re-identification").
* Common foreign terms (such as “en masse”) are roman.
* Companies are always singular. So, for example, “Apple emphasizes the
value of aesthetics in its product line. Consequently, it dominates the
digital-music market” is correct. “Apple emphasize the value of
aesthetics in their product line. They dominate the digital-music
market” is _not_. (Also applies to generic terms “organization,” “team,”
“group,” etc.)
* Do not stack admonitions, sidebars, or headings.
* Do not use a hyphen between an adverb and the word it modifies. So,
“incredibly wide table” rather than “incredibly-wide table.”
* Introduce unnumbered code blocks with colons.
* Use “between” for two items, “among” for three or more. Use “each
other” for two, “one another” for three or more.
* Use the American spellings of words when they differ.
* We advise using a conversational, user-friendly tone that assumes the
reader is intelligent but doesn’t have this particular knowledge
yet—like an experienced colleague onboarding a new hire. First-person
pronouns, contractions, and active verbs are all encouraged.
(Copyeditors: please check with your production editor if you wish to
suggest global changes to tone.)
* When referring to software elements or labels, always capitalize words
that are capitalized on screen. Put quotes around any multiword element
names that are lowercase or mixed case on screen and would thus be hard
to distinguish from the rest of the text (e.g., Click “Don’t select
object until rendered” only if necessary.)